import './ui-kit.scss';
import '../form-elements/form-elements';
import '../cards/cards';

require('../../img/logo.svg');
require('../../img/input-dropdown.svg');
require('../../img/dropdown-nav.svg');
require('../../img/arrow-forward.svg');
require('../../img/check-arrow.jpg');
require('../../img/favorite.svg');
require('../../img/favorite-border.svg');
require('../../img/star.jpg');
require('../../img/star-border.jpg');
require('../../img/user.jpg');
require('../../img/arrow-forward-white.svg');
require('../../img/smile.svg');
require('../../img/house.svg');
require('../../img/scroll-arrow.svg');
require('../../img/888.jpg');
require('../../img/840.jpg');
require('../../img/logo-color.svg');
require('../../img/twitter.svg');
require('../../img/facebook.svg');
require('../../img/instagram.svg');
require('../../img/room-slider.jpg');